# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true
highlighter:         pygments
markdown:            redcarpet
# redcarpet:
#   extensions:          ["no_intra_emphasis", "fenced_code_blocks", "autolink", "strikethrough", "superscript","tables", "with_toc_data"]

# Setup
title:               Akka-Stream Extensions
tagline:             'by MfgLabs'
description:         'Opensource Library providing useful primitives & resources for Akka Stream.'
url:                 http://mfglabs.github.com/akka-stream-extensions
baseurl:             /akka-stream-extensions
apidocs:             /akka-stream-extensions/api/
# baseurl:             ''
paginate:            5

# About/contact
author:
  name:              MfgLabs
  url:               http://mfglabs.com/
  #email:             markdotto@gmail.com

# Custom vars
version:             0.6.0

github:
  repo:              https://github.com/MfgLabs/akka-stream-extensions

# syntax-highlighting:
#   enabled :          true
#   css:               syntax.css